name: "grype"
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
jobs:
  scan-source:
    name: scan-source
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
        id: scan
        with:
          path: "."
          fail-build: true
      - uses: github/codeql-action/upload-sarif@3e6af16ff035267728e2ebc35df5d4c4cf249f81 # v3.30.3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
